name: Trigger Azure Machine Learning jobs on dev and prod data

on:
  push:
    branches:
      - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/dev_job.yml --resource-group "AzureML-tutorial" --workspace-name "nabk-ml-ws" --stream

  production:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs:
      - experiment
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/prod_job.yml --resource-group "AzureML-tutorial" --workspace-name "nabk-ml-ws" --stream

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs:
      - production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Deploy to endpoint
      run: |
        az configure --defaults workspace="nabk-ml-ws" group="AzureML-tutorial"
        az ml online-endpoint update --name "diabetes-prod-endpoint" -f endpoints/create-endpoint.yml
        JOB_NAME=$(az ml job list --query "[?experiment_name == 'diabetes-data-prod'].name | [0]" --resource-group "AzureML-tutorial" --workspace-name "nabk-ml-ws" | tr -d '"')
        az ml model create --name "mir-sample-sklearn-mlflow-model" --type "mlflow_model" --path "azureml://jobs/$JOB_NAME/outputs/artifacts/model"
        az ml online-deployment update --name sklearn-deployment --endpoint "diabetes-prod-endpoint" -f endpoints/sklearn-deployment.yml --all-traffic