name: Manually trigger an Azure Machine Learning job

on:
  push:
    branches:
      - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/dev_job.yml --resource-group "AzureML-tutorial" --workspace-name "nabk-ml-ws" --stream

  production:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs:
      - experiment
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/prod_job.yml --resource-group "AzureML-tutorial" --workspace-name "nabk-ml-ws"